### ISSUE TITLE
[Symfony][docs] Need to register custom DBAL types

### ISSUE THREAD

**Issue by teohhanhui** [jsor/doctrine-postgis#13]
`bin/console doctrine:schema:validate` gives:

> [Mapping]  FAIL - The entity-class '...' mapping is invalid:
> - The field '...' uses a non-existant type 'geometry'.

This is solved by adding the custom DBAL types to `app/config/config.yml`:

``` yaml
doctrine:
    dbal:
        types:
            geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
            geometry: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
            raster: 'Jsor\Doctrine\PostGIS\Types\RasterType'
```

**Comment by teohhanhui** [comment]
Note: `Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber` was already registered as a service:

``` yaml
# app/config/services.yml
services:
    app.jsor_doctrine_postgis.subscriber.doctrine.orm_schema:
        class: 'Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber'
        public: false
        tags:
            - name: 'doctrine.event_subscriber'
              connection: 'default'
              priority: 0
```

but I still received the above errors (warnings?).
