### ISSUE TITLE
Schema update with Point field fails.

### ISSUE THREAD

**Issue by julianrubisch** [jsor/doctrine-postgis#18]
I've got an entity mapping declaration like this:

```
/**
* @ORM\Column(name="location", type="geometry", options={"geometry_type"="POINT"})
*
* @Expose
*/
private $location;
```

When I run `php app/console doctrine:schema:update` in Symfony, it fails:

```
Unknown database type point requested, Doctrine\DBAL\Platforms\PostgreSQL92Platform may not support it.
```

PostGIS, is, of course, installed and activated as an extension.

Is this a bug, or do I have to configure this elsewhere?

I'm using version 1.1.0 of doctrine-postgis. Thanks!

**Comment by jsor** [comment]
Did you correctly setup the Schema subscriber? Looks like this is an exception thrown while inspecting the database.

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.

**Comment by julianrubisch** [comment]
I'm using Symfony (2.8), so I set it up using `services.yml`:

```
doctrine.postgis.ormschemaeventsubscriber:
        class: Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber
        tags:
           - { name: doctrine.event_subscriber, connection: default }
```
