### ISSUE TITLE
Strange behaviour using Symfony 2.8 and doctrine postgis

### ISSUE THREAD

**Issue by carterunderscore** [jsor/doctrine-postgis#20]
Hello,
I'm using doctrine-postgis 1.1.2 with Symfony 2.8 and I have a strange behaviour.
When I clean cache and run for the first time my script, everything is fine.

` echo $ouvrage->getGeometry() . "\n";`

returns something like this 

> SRID=4326;POINT(2.3344311729 49.0224338684)

When I run for the second time the same code, here is what I get

> 0101000020E610000087F23240EAAC0240E68CED1CDF824840

It's like 

Here is my services.yml entries

`services:

    app.jsor_doctrine_postgis.subscriber.doctrine.orm_schema:
        class: Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber
        public: false
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 100000  }`

I have also tested with priority 0 and no priority, no differences.

Any ideas for resolving it are welcome!

Matthieu

**Comment by jsor** [comment]
Could you setup a minimal reproducible test case? It's hard to say without seeing the entities, configurations and what kind of caches you're using.

**Comment by carterunderscore** [comment]
Creating the reproducible test case, I've solved my issue adding this to my config.yml file

```yaml
doctrine:
    dbal:
        types:
             geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
             geometry: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
             raster: 'Jsor\Doctrine\PostGIS\Types\RasterType' 
```

Without this lines, no errors on doctrine schema validation or on running-time but a random behavior.

Matthieu
