### ISSUE TITLE
Set-up problem

### ISSUE THREAD

**Issue by maxthev** [jsor/doctrine-postgis#3]
Hi ! i'm trying to use your doctrine-postgis extension but i have some trouble.

the "installation" part is ok, but then you said : 

```
**All you have to do is, to register an event subscriber.**
use Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber;
$entityManager->getEventManager()->addEventSubscriber(new ORMSchemaEventSubscriber());
```

I don't understand where to put this or what i need to do with this.

Thanks
https://github.com/jsor/doctrine-postgis/issues/new#fullscreen

**Comment by jsor** [comment]
This depends on how you use and setup Doctrine. Are you using it with Symfony or any other framework?

**Comment by maxthev** [comment]
Symfony, with config in yml.

**Comment by jsor** [comment]
See http://symfony.com/doc/current/cookbook/doctrine/event_listeners_subscribers.html

Your config would be something like:

``` yaml
services:
    doctrine_postgis_subscriber_default:
        class: Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
```

**Comment by maxthev** [comment]
and then, command like :

doctrine:schema:update or doctrine:mapping:import will work ?

thank you =)

**Comment by maxthev** [comment]
I created the service, but in don't see any differences.

in my database table, i have some column :

(....other column....)
coordinates_point POINT,
coordinates GEOGRAPHY(POINT,4326),
(....other columns....)

I don't understand how to use them with doctrine, doctrine don't want my "point",

```
**[Doctrine\DBAL\DBALException]
  Unknown database type point requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.**
```

i tried to update my entities like this :

```
/**
     * @var point
     *
     * @ORM\Column(name="coordinates_point", type="point", nullable=true)
     */
```

TO

```
/**
     * @var geometry
     *
     * @ORM\Column(name="coordinates_point", type="geometry", options={"geometry_type"="POINT"}, nullable=true)
     */
```

and then doctrine:schema:update, but it's the same error...

**Comment by jsor** [comment]
This error occures while DBAL inspects your database and don't have a DBAL type for the POINT column. You need to change the column type manually in your database.

**Comment by maxthev** [comment]
it's seems it beginning to work, thank's a lot !

**Comment by jsor** [comment]
Glad to hear. Let me know how it goes :)
I'm closing this for now, feel free to reopen if needed.

**Comment by maxthev** [comment]
yoooops to late x) i don't know how to 're-open', guess i will juste write another comment here ? 

now i have : 

```
 [Doctrine\DBAL\DBALException]
  Unknown database type geometry requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
```

looks like "geography" works well but "geometry" does not ...

**Comment by jsor** [comment]
Hmm...can you try to register the DBAL type manually:

``` yaml
doctrine:
    dbal:
        types:
            geometry: Jsor\Doctrine\PostGIS\Types\GeometryType
```
