### ISSUE TITLE
Event subscriber

### ISSUE THREAD

**Issue by vincent-boulard** [jsor/doctrine-postgis#43]
Hello,

I do not know how to setup an event subscriber and I don't understand the Symfony's documentation.

I have this error : 

> Attempted to load class "ORMSchemaEventSubscriber" from namespace "Jsor\Doctrine\PostGIS\Event".
Did you forget a "use" statement for another namespace?

i don't know what to do to implements correctly postgis to my symfony 4.2 application

Can someone help me ?

**Comment by jsor** [comment]
Just to be sure: have you actually installed this package via composer?

**Comment by vincent-boulard** [comment]
Yes, I followed the installation part and I created the service in my yaml configuration

**Comment by jsor** [comment]
I tried to reproduce it and did:

```bash
composer create-project symfony/website-skeleton test
cd test/
composer require jsor/doctrine-postgis
```

and then added the following to `config/services.yaml`

```yaml
services:
    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
```

Everything worked as expected.

Could you provide a minimal test case to reproduce this?
